import 'dart:convert';
import 'package:cloud_firestore/cloud_firestore.dart';

// Helper functions for JSON
TaskModel taskModelFromJson(String str) => TaskModel.fromJson(json.decode(str));
String taskModelToJson(TaskModel data) => json.encode(data.toJson());

class TaskModel {
  String? id;
  String title;
  String description;
  DateTime? createdAt;

  TaskModel({
    this.id,
    required this.title,
    required this.description,
    this.createdAt,
  });

  // Generated by QuickType (Task 3 Requirement)
  factory TaskModel.fromJson(Map<String, dynamic> json) => TaskModel(
        id: json["id"],
        title: json["title"],
        description: json["description"],
        createdAt: json["createdAt"] == null 
            ? null 
            : DateTime.parse(json["createdAt"]),
      );

  // Generated by QuickType (Task 3 Requirement)
  Map<String, dynamic> toJson() => {
        "id": id,
        "title": title,
        "description": description,
        "createdAt": createdAt?.toIso8601String(),
      };

  // Firestore Helper (Task 5 Requirement)
  factory TaskModel.fromFirestore(DocumentSnapshot doc) {
    Map<String, dynamic> data = doc.data() as Map<String, dynamic>;
    return TaskModel(
      id: doc.id,
      title: data['title'] ?? '',
      description: data['description'] ?? '',
      createdAt: data['createdAt'] != null 
          ? (data['createdAt'] as Timestamp).toDate() 
          : null,
    );
  }

  // Firestore Helper (Task 5 Requirement)
  Map<String, dynamic> toFirestore() {
    return {
      'title': title,
      'description': description,
      'createdAt': createdAt ?? FieldValue.serverTimestamp(),
    };
  }
}